name: dictionary
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  introduction_screen: ^3.1.8
  internet_connection_checker: ^1.0.0+1
  get_storage: ^2.1.1
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  carousel_slider: ^4.2.1
  restart_app: ^1.1.2
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0
  file_picker: ^5.2.11
  url_launcher: ^6.1.10
  share_plus: ^4.5.3
  flutter_dotenv: ^5.0.2
  logger: ^1.3.0
  sentry_flutter: ^7.5.0
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

# Splash Screen Config
flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - .env.production
    - .env.development

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins_Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins_Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins_ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins_SemiBold.ttf
          weight: 500

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  generate_icons: flutter pub run flutter_launcher_icons:main
  generate_splash_screen: flutter pub run flutter_launcher_icons:main
